"""Input packaging only. Expected numbers are literal, never generated by the engine."""

import copy

from dsio_inventory_engine.inventory_contracts.training import content, normalize
from dsio_inventory_engine.inventory_contracts.values import digest
from dsio_inventory_engine.training.demo import build_demo_request


def reseal_training(data):
    data = normalize(copy.deepcopy(data))
    data["content_hash"] = digest(content(data))
    return data


def training_fixture():
    data = build_demo_request().to_dict()
    data["items"] = [next(i for i in data["items"] if i["item_id"] == "NORMAL")]
    data["items"][0].update(item_id="A", moq="0", lot_multiple="1")
    data.update(train_weeks=1, validation_weeks=1, test_weeks=4)
    data["calendar"] = data["calendar"][:84]
    data["demand"] = [
        {"item_id": "A", "uom": "EA", "yyyyww": c["yyyyww"], "demand_qty": "10"}
        for c in data["calendar"]
    ]
    data["scenarios"] = [next(s for s in data["scenarios"] if s["scenario_id"] == "BASE")]
    return reseal_training(data)
